WITH GENERATION1 AS (
  SELECT ID
  FROM ECOLI_DATA
  WHERE PARENT_ID IS NULL
),
GENERATION2 AS (
  SELECT ID
  FROM ECOLI_DATA
  WHERE PARENT_ID IN (SELECT ID FROM GENERATION1)
)
SELECT e.ID
FROM ECOLI_DATA e
WHERE e.PARENT_ID IN (SELECT ID FROM GENERATION2);