WITH RANK_OF_COLONY_SIZE AS (
    SELECT ID, RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS R 
    FROM ECOLI_DATA
)

SELECT ID, 
    CASE WHEN R <= (SELECT COUNT(*) FROM ECOLI_DATA) * 0.25 THEN 'CRITICAL'
         WHEN R <= (SELECT COUNT(*) FROM ECOLI_DATA) * 0.5 THEN 'HIGH'
         WHEN R <= (SELECT COUNT(*) FROM ECOLI_DATA) * 0.75 THEN 'MEDIUM'
         WHEN R <= (SELECT COUNT(*) FROM ECOLI_DATA) THEN 'LOW' END AS COLONY_NAME
FROM ECOLI_DATA NATURAL JOIN RANK_OF_COLONY_SIZE
ORDER BY ID;