WITH HISTORY AS (
    SELECT *, 
    CASE 
        WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 90 THEN "90일 이상"
        WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 30 THEN "30일 이상"
        WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 7 THEN "7일 이상"
        ELSE NULL 
    END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)

SELECT H.HISTORY_ID, 
ROUND(IF(H.DURATION_TYPE IS NULL, C.DAILY_FEE * (TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1), 
   C.DAILY_FEE * (TIMESTAMPDIFF(DAY, H.START_DATE, H.END_DATE) + 1) * (1 - P.DISCOUNT_RATE / 100))) AS FEE 
FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN HISTORY H ON C.CAR_ID = H.CAR_ID 
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE AND H.DURATION_TYPE	= P.DURATION_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;
