-- 코드를 입력하세요
WITH TOTAL AS (
    SELECT 
        FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
    FROM 
        (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM FIRST_HALF 
        GROUP BY FLAVOR
        UNION ALL
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER FROM JULY 
        GROUP BY FLAVOR) AS TEMP
    GROUP BY FLAVOR
)

SELECT FLAVOR FROM TOTAL
ORDER BY TOTAL_ORDER DESC
LIMIT 3;
