-- 코드를 입력하세요
SELECT PT_NAME, PT_NO, GEND_CD, AGE, IF(TLNO IS NULL, "NONE", TLNO) AS TLNO FROM PATIENT 
WHERE PATIENT.GEND_CD = "W" AND PATIENT.AGE <= 12
ORDER BY PATIENT.AGE DESC, PATIENT.PT_NAME ASC;