-- 코드를 작성해주세요
WITH MAX_SIZE_OF_COLONY_BY_YEAR AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR
)
SELECT M.YEAR, M.MAX_SIZE_OF_COLONY - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID 
FROM ECOLI_DATA E JOIN MAX_SIZE_OF_COLONY_BY_YEAR M ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY M.YEAR, YEAR_DEV;